### PR TITLE
fix typescript build issues

### PR DESCRIPTION
**Pull request by spiralw**
same as Tupperbox/DiscordRest#1

```
$ npm run build
> detritus-client-socket@0.8.3 build
> tsc

src/decompressors/zlib.ts:24:5 - error TS2322: Type '"pako"' is not assignable to type '"zlib"'.

24     Inflate.type = type;
       ~~~~~~~~~~~~

src/decompressors/zlib.ts:75:12 - error TS2678: Type '"pako"' is not comparable to type '"zlib"'.

75       case DependencyTypes.PAKO: {
              ~~~~~~~~~~~~~~~~~~~~

src/decompressors/zlib.ts:116:12 - error TS2678: Type '"pako"' is not comparable to type '"zlib"'.

116       case DependencyTypes.PAKO: {
               ~~~~~~~~~~~~~~~~~~~~

src/decompressors/zlib.ts:141:12 - error TS2678: Type '"pako"' is not comparable to type '"zlib"'.

141       case DependencyTypes.PAKO: {
               ~~~~~~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: src/decompressors/zlib.ts:24
```

### CODE REVIEW

**Comment by Roryl-c** [comment]
What's your typescript version?

**Comment by spiralw** [comment]
4.8.4: https://github.com/ApparyllisOrg/Spot/blob/main/package.json#L19

**Comment by spiralw** [comment]
worth noting I also had this issue when trying to build it by git cloning this repo

**Comment by Roryl-c** [comment]
huh, only way I could repro this was by compiling with typescript v4.9.4, which apparently is now a tad bit smarter. anyway seems like forward compatibiltiy is good

**Pull request merged**
